Gizaw.commuter test
amhakindu/Rideshare pull request #71
Opened 2023-07-25 05:10 UTC by GizawAAiT

Title: Fixing Feedback Tests, Adding GetCommuterStatusQueryHandler Test, and Error Fixes in RateTests

Description:
This pull request (PR) includes several updates and improvements to the existing codebase. Here's a breakdown of the changes:

Feedback Tests Modification:
I have addressed issues with the feedback tests to ensure they work as intended.

New Test for GetCommuterStatusQueryHandler:
I have introduced a new test for the GetCommuterStatusQueryHandler to validate its functionality. 

Error Fixes in RateTests:
I have investigated and resolved errors present in the RateTests which is related to namespace and other similar things.

2023-07-30 22:16 UTC, tedblackson commented on Rideshare.Application/Common/Dtos/Commuter/Validators/CommuterStatisticsRequestValidator.cs
> +    private bool BeValidYearType(int? year)
This is not necessary, it will be handled automatically by the framework

2023-07-30 23:13 UTC, tedblackson requested changes

2023-07-30 23:13 UTC, tedblackson commented on Rideshare.UnitTests/Commuters/GetCommuterStatusQueryHandlerTest.cs
> +
set up  the method in the UserMockRepository

2023-07-30 23:13 UTC, tedblackson commented on Rideshare.UnitTests/Commuters/GetCommuterStatusQueryHandlerTest.cs
> +		[Fact]
You should handle the dependency injection in a constructor , How are you planing to add another test in this file if you did the dependency injection in one fact

2023-07-30 23:13 UTC, tedblackson commented on Rideshare.UnitTests/Feedbacks/DeleteFeedbackCommandHandlerTest.cs
> +			catch (Exception ex) {
What kind of exception are we expecting, make sure it is the kind we expected

2023-07-30 23:13 UTC, tedblackson commented on Rideshare.UnitTests/Feedbacks/UpdateFeedbackCommandHandlerTest.cs
> +			var feedback = await _mockUnitOfWork.Object.FeedbackRepository.Get(feedBackDto.Id);
check all the properties

2023-07-31 15:07 UTC, GizawAAiT commented
Having carefully reviewed all the comments mentioned earlier, I have made the necessary adjustments to those files. Now you can check it again. thank you for the valuable comments.

2023-08-10 23:36 UTC, merged